### PR TITLE
Middleware/interceptor dependency resolution algorithm

### PR DESCRIPTION
**Pull request by nilern**
Starting point for #33.

### CODE REVIEW

**Comment by nilern** [comment]
I have a bad feeling about the 3-arity post-order. Maybe it should instead take an optional parameter map.

**Comment by ikitommi** [comment]
how would the parameter map work? I would like to test with this, so merging into develop now.

**Comment by ikitommi** [comment]
oh, it didn't work. https://circleci.com/gh/metosin/reitit/1604

**Comment by ikitommi** [comment]
fixed

**Pull request merged**
