### PR TITLE
Add an example project with Integrant

### PR DESCRIPTION
**Pull request by dawran6**
This PR addresses #265 

Feedbacks are welcome.
Currently, the project is minimal. The system only contains two keys: `:example/jetty` and `:example/handler`. I can certainly add more features.

### CODE REVIEW

**Comment by ikitommi** [comment]
Hi. Looks great! What do you think of adding [integrant repl](https://github.com/weavejester/integrant-repl) to the mix. We use that, makes the developer Experience much better, when there are more namespaces to cover.

**Comment by dawran6** [comment]
Yup! I like the idea. I use Integrant repl myself. It makes sense to also show the whole developer experience in the example.

**Comment by dawran6** [comment]
The `integrant/repl` related functions are moved to the `user` ns.
I also removed the `example.server/server` atom since `integrant/repl` tracks the system state for me. Thanks for reviewing @ikitommi !

**Comment by ikitommi** [comment]
Awesome, thanks!

**Pull request merged**
