### PR TITLE
URL-encode supplied routes?

### PR DESCRIPTION
**Pull request by KingMob**
## URL-encoding supplied routes

At the moment, this should probably be more of a discussion. The initially committed code will happily convert your routes, but runs into issues if *you've* already converted those routes, since it'll double-encode the %'s (turning `/spaced%20path` into `/spaced%2520path`). What to do in this situations is not exactly clear. I see several options:

1. Always encode the routes. Users will have to be educated to never encode the routes themselves. Probably fine for hand-written routes, but I can easily imagine tool/DB-generated routes already being encoded.
2. Never encode the routes. Users will have to know about this, too, but a lot of the time, cursory debugging will reveal the issue if they run into errors. Has the appeal of *forcing* users to supply valid routes, but less friendly. I suspect most users shy away from reserved chars to be safe, so this is probably ok.
3. Add a flag. Set a default, but allow users to change it, either globally or per route. Adds complexity but flexibility.
4. Try to determine if percent-encoding is present on behalf of the user. User-friendly, but impossible to always get right without, say, natural-language processing, and probably not even then. (E.g., how do you handle `/100%best-product`?)

I'm leaning towards 2 or 3. 2 is zero work, other than maybe updating the docs, or issuing a warning if reserved chars are encountered.

Thoughts?

### CODE REVIEW

**Comment by KingMob** [comment]
@ikitommi Any thoughts?

**Comment by ikitommi** [comment]
Sorry for taking so long time. 

Just tested with some 3rd party routers:

* `"/a b"`:
  * compojure -> fail
  * express -> fail
  * sinatra -> ok
* `"/100%best-product`
  * compojure -> ok
  * express -> ok
  * sinatra -> fail

from a browser:

* `/100%best-product` is sent as `/100%best-product`
* `/a b` is sent as `/a%20b`

... so none of those routers can handle these correctly.

To fix this for good, we should know how the clients send the uris. If this would be fixed, I should be pluggable - as the core router can be used in non-http routing too (routing in queuing system, which might allow all chars).

Are you actually facing this issue? if not, I would suggest not to fix this, just document it = 2, would work like compojure & express - and most of the routers out there.

**Comment by KingMob** [comment]
Nah, not actually facing this issue. Decoding yes, encoding no.

I changed the PR to just add a note in the docs about not encoding paths. If you like it, cool, if not, no worries!

**Comment by ikitommi** [comment]
Big thanks!

**Comment by KingMob** [comment]
👍

**Pull request merged**
