### PR TITLE
Update to latest ring-swagger-ui

### PR DESCRIPTION
**Pull request by heyarne**
This updates `ring-swagger-ui`, thereby updating `swagger-ui` to version 3. Note that `swagger-ui` 3.x [supports different versions of the OpenAPI spec](https://github.com/swagger-api/swagger-ui/tree/a24957e8ce938de162a05a02f166b3120b1a1b06) compared to the one used before. This should not be a problem because the `swagger.json` generated by `reitit-swagger` uses the `swagger` fromat `2.0`, at least in my case. I don't know if there are cases where this might cause a problem.

### CODE REVIEW

**Comment by miikka** [comment]
I've intentionally kept not updating it because I like the version 2 more. But maybe we should move on with the times. :P

**Comment by ikitommi** [comment]
Same here! One option would be to push the ui's into separate resource dirs, e.g. `/resources/swagger/2` and `/resources/swagger/latest`. Not suggesting, but an option.

**Comment by heyarne** [comment]
> I've intentionally kept not updating it because I like the version 2 more. But maybe we should move on with the times. :P

What exactly did you like more about it? I had a problem with a swagger file created with `reitit-swagger` that caused an error with version 2 but not version 3, which is why I upgraded. I can't share the file here unfortunately, but maybe in private / the #clojurians slack.

**Comment by ikitommi** [comment]
I tested with few apps, seems to work ok. Let's use the latest. One can always revert to older one if needed.

**Comment by ikitommi** [comment]
Oh, but there is now a merge conflict. Could you please resolve that? Also, a mention to the docs on how to use the 2.* UI would be great.

**Comment by heyarne** [comment]
Let me know if that works for you or if you need anything else!

**Comment by ikitommi** [comment]
thanks!

**Pull request merged**
