### PR TITLE
Faster keywordize

### PR DESCRIPTION
**Pull request by bsless**
Implement walk with protocols and keywordize keys with it.
Gives about 2x speedup

left to do: decide on an implementation for cljs

### CODE REVIEW

**Comment by bsless** [comment]
@ikitommi do you want to extend this solution to cljs or keep it just for clj?

**Comment by bsless** [comment]
Decided to split the implementation off only for Clojure since cljs is built differently, don't even know how `walk` is implemented for it

**Comment by bsless** [comment]
@ikitommi are there any blocking items for a review? I'd be happy to clear them if so.

**Comment by bsless** [comment]
Open question - how can we be sure this does not introduce regressions for users who upgrade?

**Comment by bsless** [comment]
Added generative test to validate my assumption

**Comment by ikitommi** [comment]
Thanks!

**Pull request merged**
