### PR TITLE
Upgrade to bat-test and make Circle test summaries work

### PR DESCRIPTION
**Pull request by miikka**
See https://circleci.com/gh/metosin/reitit/285 for an example of a test summary.

### CODE REVIEW

**Comment by miikka** [comment]
Hmm, why do we have both Circle and Travis running the same tests?

**Comment by ikitommi** [comment]
Nice. I guess we can dump travis then?

**Comment by miikka** [comment]
Well, Travis does run the cljs tests and Circle doesn't. But maybe Circle could run both?

**Comment by ikitommi** [comment]
indeed

**Comment by miikka** [comment]
I'll merge this and try to dump Travis later.

**Pull request merged**
